---
title: "TADPOLE"
author: "José Tamez-Peña"
date: "October 20, 2017"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r, echo = FALSE}
knitr::opts_chunk$set(collapse = TRUE, warning = FALSE, message = FALSE,comment = "#>")
```

```{r Libraries, echo = FALSE}

library("epiR")
library("FRESA.CAD")
library(network)
library(GGally)
library("e1071")

TADPOLE_predictors <- read.delim("PredictorsList.txt")

load(file="D3Imputed.RDATA")
load(file="TEST_TADPOLEMRI.RDATA")
load(file="TRAIN_TADPOLEMRI.RDATA")
load(file="trainTadploe.norm.RDATA")
load(file="testTadploe.norm.RDATA")
load(file="D3.norm.RDATA")

```

```{r spliting by visit}
months <- c(0,3,6,12,18,24,30,36,42,48,54,60,66,72,78,84,90,96,102,108,114,120)

VISIT_TRAINCROSSMRI <- list()
VISIT_TESTCROSSMRI <- list()
i = 1;
for (j in months )
{
  VISIT_TRAINCROSSMRI[[i]] <- subset(trainTadploe.norm,Month==j)
  VISIT_TESTCROSSMRI[[i]] <- subset(testTadploe.norm,Month==j)
  i = i + 1
}
sampledcolumns <- c("RID",as.character(TADPOLE_predictors[,1]));

testLastTimePointWithNL <- subset(testTadploe.norm,LastCompleteObs==1 & LastDX2=="NL")[,sampledcolumns]
testLastTimePointWithMCI <- subset(testTadploe.norm,LastCompleteObs==1 & LastDX2=="MCI")[,sampledcolumns]
testLastTimePointWithAD <- subset(testTadploe.norm,LastCompleteObs==1 & LastDX2=="Dementia")[,sampledcolumns]

trainLastTimePointWithNL <- subset(trainTadploe.norm,LastCompleteObs==1 & LastDX2=="NL")
trainLastTimePointWithMCI <- subset(trainTadploe.norm,LastCompleteObs==1 & LastDX2=="MCI")
trainLastTimePointWithAD <- subset(trainTadploe.norm,LastCompleteObs==1 & LastDX2=="Dementia")
rownames(trainLastTimePointWithAD) <- trainLastTimePointWithAD$RID


testWithNL <- subset(testTadploe.norm,LastDX2=="NL")[,sampledcolumns]
testWithMCI <- subset(testTadploe.norm,LastDX2=="MCI")[,sampledcolumns]
testWithAD <- subset(testTadploe.norm,LastDX2=="Dementia")[,sampledcolumns]

```


```{r univariate Ventricle ICV to Dementia}
CASESMCI <- NULL
j=1
lotmpss <-  subset(trainTadploe.norm,LastCompleteObs==1)

for (j in 1:length(VISIT_TRAINCROSSMRI) )
{
  tmpss <-  subset(VISIT_TRAINCROSSMRI[[j]],BDX==2 & LastCompleteObs==0)
  rids <- as.character(tmpss$RID)
  DADAS13 <- lotmpss[rids,"ADAS13"]-tmpss$ADAS13
  timetolast <- lotmpss[rids,"Years_bl"]-tmpss$Years_bl;
  CASESMCI <- rbind(CASESMCI,cbind(DADAS13,timetolast,tmpss[,sampledcolumns]))
}

hist(CASESMCI$DADAS13)
CASESMCI <- CASESMCI[complete.cases(CASESMCI),]
CASESMCI$ICV <- NULL
#CASESMCI$ADAS13 <- NULL
CASESMCI$timetolast2 <- CASESMCI$timetolast*CASESMCI$timetolast
CASESMCI$timetolast3 <- log(CASESMCI$timetolast)
CASESMCI$timetolast_40CCMP <- CASESMCI$ST40CCMP*log(CASESMCI$timetolast)
CASESMCI$timetolast_MeanCV <- CASESMCI$MeanCV*log(CASESMCI$timetolast)
TADPOLE_predictors <- read.delim("PredictorsList.txt")

rownames(TADPOLE_predictors) <- TADPOLE_predictors$Var
#TADPOLE_predictors <- subset(TADPOLE_predictors,Var != "ADAS13")
TADPOLE_predictors <- subset(TADPOLE_predictors,Var != "ICV")

timename <- c("timetolast","timetolast")
names(timename) <- colnames(TADPOLE_predictors)
TADPOLE_predictors <- rbind(t(timename),TADPOLE_predictors)
timename <- c("timetolast2","timetolast2")
names(timename) <- colnames(TADPOLE_predictors)
TADPOLE_predictors <- rbind(t(timename),TADPOLE_predictors)
timename <- c("timetolast3","timetolast3")
names(timename) <- colnames(TADPOLE_predictors)
TADPOLE_predictors <- rbind(t(timename),TADPOLE_predictors)
timename <- c("timetolast_40CCMP","timetolast_40CCMP")
names(timename) <- colnames(TADPOLE_predictors)
TADPOLE_predictors <- rbind(t(timename),TADPOLE_predictors)
timename <- c("timetolast_MeanCV","timetolast_MeanCV")
names(timename) <- colnames(TADPOLE_predictors)
TADPOLE_predictors <- rbind(t(timename),TADPOLE_predictors)

ADAS13_RankFeaturesRaw <- univariateRankVariables(variableList = TADPOLE_predictors,
	                                            formula = "DADAS13 ~ 1",
	                                            Outcome = "DADAS13",
	                                            data = CASESMCI, 
	                                            categorizationType = "Raw", 
	                                            type = "LM", 
	                                            rankingTest = "Ztest",
	                                            description = "Description",
                                               uniType="Regression")
ADAS13_RankFeaturesRaw["timetolast",]
ADAS13_RankFeaturesRaw["timetolast2",]
ADAS13_RankFeaturesRaw["timetolast3",]
ADAS13_RankFeaturesRaw["ADAS13",]
```


```{r Modeling ADAS13 time in MCI}
compute = TRUE
numberofRepp = 20
numberofFolds = 3
numberOfTrials = 5
allformulas <- character();
logitcor <- numeric();
logitMAD <- numeric();

testWithMCI$ADAS13 <- numeric(nrow(testWithMCI))
alltestpredicts <- NULL
allD3predicts <- NULL
allforcasttestPredicts <- NULL
repp = 1
for ( repp in 1:numberofRepp)
{

  ids_ca <- unique(as.character(CASESMCI$RID))
	casefolds <- cvTools::cvFolds(length(ids_ca), numberofFolds,1, "random");
	
	 j=1
	for (j in 1:numberofFolds)
	{

	  sampleIDS_TimeADAS13 <- ids_ca[casefolds$subsets[casefolds$which != j,]];

    trainTime_ADAS13 <- subset(CASESMCI,RID %in% sampleIDS_TimeADAS13)
    testTime_ADAS13 <- subset(CASESMCI,!(RID %in% sampleIDS_TimeADAS13))
    testD3 <- subset(D3.norm,!(RID %in% sampleIDS_TimeADAS13))
    testD3$ADAS13 <- rep(0,nrow(testD3))
    
    print(length(unique(as.character(trainTime_ADAS13$RID))))
    print(length(unique(as.character(testTime_ADAS13$RID))))
    
    ids <- unique(as.character(trainTime_ADAS13$RID))
    sys_times <- NULL;
    Time_ADAS13 <- list();
    n=1
    hist(CASESMCI$timetolast)
    if (compute)
    {
      for (n in 1:numberOfTrials)
      {
        singlecaseTime_ADAS13 <- NULL;
        for (i in ids)
        {
          case1 <- subset(trainTime_ADAS13,RID==i)
          caserows <- nrow(case1)
          if (caserows>1)
          {
            singlecaseTime_ADAS13 <- rbind(singlecaseTime_ADAS13,case1[sample(caserows, 1),])
          }
          else
          {
            singlecaseTime_ADAS13 <- rbind(singlecaseTime_ADAS13,case1)
          }
        }
        singlecaseTime_ADAS13$RID <- NULL;
        print(nrow(singlecaseTime_ADAS13))
        sys_times <- rbind(sys_times,system.time(Time_ADAS13[[n]] <- FRESA.Model(DADAS13 ~ 1,singlecaseTime_ADAS13,filter.p.value = 0.0001)))
        pr <- predict(Time_ADAS13[[n]]$BSWiMS.model,testTime_ADAS13)
        cat("MAD:",mean(abs(pr-testTime_ADAS13$DADAS13)))
        plot(pr~testTime_ADAS13$DADAS13)
      }
      save(sys_times,file=paste("sys_times_Time_ADAS13_MCI",numberOfTrials,j,repp,"q.RDATA",sep="_"))
      save(Time_ADAS13,file=paste("Time_ADAS13_MCI",numberOfTrials,j,repp,"q.RDATA",sep="_"))
    }
    else
    {
      load(file=paste("Time_ADAS13_MCI",numberOfTrials,j,repp,"q.RDATA",sep="_"))
      sampleIDS_TimeADAS13 <- NULL;
    }
    
    baggedformula <- character();
    for (n in 1:numberOfTrials)
    {
      if (length(Time_ADAS13[[n]]$BSWiMS.model$coefficients)>1)
      {
        baggedformula <- append(baggedformula,Time_ADAS13[[n]]$BSWiMS.model$formula)
      }
      if (!compute)
      {
    	  idst <- unlist(str_split(rownames(Time_ADAS13[[n]]$bootstrappedModel$data),"_"))
        sampleIDS_TimeADAS13 <- append(sampleIDS_TimeADAS13,idst[2*(0:(length(idst)-1))+1])
      }
    }
    
    if (!compute)
    {
    	sampleIDS_TimeADAS13 <- unique(sampleIDS_TimeADAS13)
      trainTime_ADAS13 <- subset(CASESMCI,(RID %in% sampleIDS_TimeADAS13))
      testTime_ADAS13 <- subset(CASESMCI,!(RID %in% sampleIDS_TimeADAS13))
      
      testD3 <- subset(D3.norm,!(RID %in% sampleIDS_TimeADAS13))
      testD3$ADAS13 <- rep(0,nrow(testD3))
    }

    mp <- medianPredict(as.character(baggedformula),trainTime_ADAS13,testTime_ADAS13,predictType ="linear",type="LM")
    alltestpredicts <- rbind(alltestpredicts,cbind(testTime_ADAS13$DADAS13,mp$medianPredict))
    plot(testTime_ADAS13$DADAS13~mp$medianPredict)
    ct <- cor.test(testTime_ADAS13$DADAS13,mp$medianPredict)
    logitcor <- append(logitcor,ct$estimate)
    res <- testTime_ADAS13$DADAS13-mp$medianPredict
    logitMAD <- append(logitMAD,mean(abs(res)))
    print(logitMAD)
    print(logitcor)
    allformulas <- append(allformulas,as.character(baggedformula))
    
    
    testWithAD_s <- subset(testTadploe.norm,LastCompleteObs==1 & BDX==2)
    testWithAD_s$DADAS13 <- numeric(nrow(testWithAD_s))
    n=1
    forcasttestPredicts <- testWithAD_s$RID
    for (n in 1:60)
    {
        timetolast <- testWithAD_s$to2018+(n-0.5)/12
        testWithAD_s$timetolast <- timetolast
        testWithAD_s$timetolast2 <- timetolast*timetolast
        testWithAD_s$timetolast3 <- log(timetolast)
        testWithAD_s$timetolast_40CCMP <- testWithAD_s$ST40CCMP*log(timetolast)
        testWithAD_s$timetolast_MeanCV <- testWithAD_s$MeanCV*log(timetolast)
        mp <- medianPredict(as.character(baggedformula),trainTime_ADAS13,testWithAD_s,predictType ="linear",type="LM")
        forcasttestPredicts <- cbind(forcasttestPredicts,mp$medianPredict+testWithAD_s$ADAS13)
    }
    allforcasttestPredicts <- rbind(allforcasttestPredicts,forcasttestPredicts)
    
    testD3 <- subset(D3.norm,!(RID %in% sampleIDS_TimeADAS13))
    testD3$DADAS13 <- rep(0,nrow(testD3))

    n=1
    forcasttestPredicts <- testD3$RID
    for (n in 1:60)
    {
        timetolast <- testD3$to2018+(n-0.5)/12
        testD3$timetolast <- timetolast
        testD3$timetolast2 <- timetolast*timetolast
        testD3$timetolast3 <- log(timetolast)
        testD3$timetolast_40CCMP <- testD3$ST40CCMP*log(timetolast)
        testD3$timetolast_MeanCV <- testD3$MeanCV*log(timetolast)
        mp <- medianPredict(as.character(baggedformula),trainTime_ADAS13,testD3,predictType ="linear",type="LM")
        tmp <- mp$medianPredict+testD3$ADAS13
        forcasttestPredicts <- cbind(forcasttestPredicts,tmp)
    }
    allD3predicts <- rbind(allD3predicts,forcasttestPredicts)

        
  }
}



write.csv(allforcasttestPredicts,file=paste(repp,"D2_ADAS13_MCI_q.csv",sep="_"))
write.csv(allD3predicts,file=paste(repp,"D3_ADAS13_MCI_q.csv",sep="_"))
rowss <- nrow(testWithAD_s)
totrep <- numberofRepp*numberofFolds
n=1
mean50CI <- NULL;
id = 1
for (id in 1:rowss)
{
  ids <- allforcasttestPredicts[id,1]
  for (n in 2:61)
  {
      dta <- allforcasttestPredicts[rowss*(0:(totrep-1))+id,n]
      mean50CI <- rbind(mean50CI,c(ids,mean(dta),as.vector(quantile(dta, probs = c(0.25, 0.75), na.rm = TRUE,names = FALSE, type = 7))))
  }
}
write.csv(mean50CI,file=paste(repp,"D2_ADAS13_MCI_mean50CI_q.csv",sep="_"))

rowss <- nrow(D3.norm)
totrep <- numberofRepp*numberofFolds
n=1
mean50CI <- NULL;
ids <- D3.norm$RID;
allD3predicts <- as.data.frame(allD3predicts)
colnames(allD3predicts) <- c("RID",paste("V",1:60,sep="_"))
for (id in ids)
{
  for (n in 2:61)
  {
      dta <- subset(allD3predicts,RID==id)[,n]
      mean50CI <- rbind(mean50CI,c(id,mean(dta),as.vector(quantile(dta, probs = c(0.25, 0.75), na.rm = TRUE,names = FALSE, type = 7))))
  }
}
write.csv(mean50CI,file=paste(repp,"D3_ADAS13_MCI_mean50CI_q.csv",sep="_"))



bp <- boxplot(alltestpredicts[,2]~rownames(alltestpredicts),plot=FALSE)
bpstatx <- bp$stats[3,]
bp <- boxplot(alltestpredicts[,1]~rownames(alltestpredicts),plot=FALSE)
bpstaty <- bp$stats[3,]
plot(bpstaty~bpstatx,main="All Tests",xlim=c(-5,35),ylim=c(-5,35))
ct <- cor.test(bpstaty,bpstatx)
cat("MAD:",mean(abs(bpstaty-bpstatx)))


```
