---
title: "TADPOLE"
author: "José Tamez-Peña"
date: "October 20, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r, echo = FALSE}
knitr::opts_chunk$set(collapse = TRUE, warning = FALSE, message = FALSE,comment = "#>")
```

```{r Libraries, echo = FALSE}

library("epiR")
library("FRESA.CAD")
library(network)
library(GGally)
library("e1071")

TADPOLE_BASIC <- read.delim("AllSubjectsWithBasicInfo.txt")
TADPOLE_CROSSMRI <- read.delim("CompleMRIObs.txt",na.strings = c("NA","","#DIV/0!"))
TADPOLE_predictors <- read.delim("PredictorsList.txt")
rownames(TADPOLE_BASIC) <- as.character(TADPOLE_BASIC$IDTIME)
rownames(TADPOLE_CROSSMRI) <- as.character(TADPOLE_CROSSMRI$ID_TP)


```

```{r subsets}
months <- c(0,3,6,12,18,24,30,36,42,48,54,60,66,72,78,84,90,96,102,108,114,120)


TRAIN_TADPOLEMRI <- subset(TADPOLE_CROSSMRI,TADPOLE_CROSSMRI$D1==1 & TADPOLE_CROSSMRI$D2==0)
TRAIN_TADPOLEBASIC <- subset(TADPOLE_BASIC,TADPOLE_BASIC$D1==1 & TADPOLE_BASIC$D2==0)
TEST_TADPOLEMRI <- subset(TADPOLE_CROSSMRI,TADPOLE_CROSSMRI$D2==1)
TEST_TADPOLEBASIC <- subset(TADPOLE_BASIC,TADPOLE_BASIC$D2==1)




```

```{r Adjusting for age and ICV}


TRAIN_TADPOLEMRI$cICV <- TRAIN_TADPOLEMRI$ICV^(1/3)
TEST_TADPOLEMRI$cICV <- TEST_TADPOLEMRI$ICV^(1/3)

rownames(TADPOLE_predictors) <- as.character(TADPOLE_predictors[,1])
prednames <- as.character(TADPOLE_predictors[-c(1:17),1])

TRAIN_TADPOLEMRI <- TRAIN_TADPOLEMRI[complete.cases(TRAIN_TADPOLEMRI[,prednames]),]
CTest_TADPOLEMRI <- TEST_TADPOLEMRI[complete.cases(TEST_TADPOLEMRI[,prednames]),]
ControlNormal <- subset(TRAIN_TADPOLEMRI,BXBL=="CN" & LastDX2=="NL" & LastVisit>2 & Month==0)
ControlNormal2 <- subset(CTest_TADPOLEMRI,BXBL=="CN" & LastDX2=="NL" & LastVisit>2 & Month==0)
ControlNormal <- rbind(ControlNormal,ControlNormal2)
sum(ControlNormal$PTGENDER==1)
sum(ControlNormal$PTGENDER==2)
hist(ControlNormal$MeanT)
hist(subset(ControlNormal,PTGENDER==1)$MeanT)
hist(subset(ControlNormal,PTGENDER==2)$MeanT)

trainTadploe.adj <- featureAdjustment(TADPOLE_predictors[prednames,], baseModel="1+AGE+cICV",data=TRAIN_TADPOLEMRI,referenceframe=ControlNormal,strata="PTGENDER", type = "LM", pvalue = 0.001)

testTadploe.adj <- featureAdjustment(TADPOLE_predictors[prednames,], baseModel="1+AGE+cICV",data=CTest_TADPOLEMRI,referenceframe=ControlNormal,strata="PTGENDER", type = "LM", pvalue = 0.001)

ControlNormal.adj <- featureAdjustment(TADPOLE_predictors[prednames,], baseModel="1+AGE+cICV",data=ControlNormal,referenceframe=ControlNormal,strata="PTGENDER", type = "LM", pvalue = 0.001)


hist(subset(ControlNormal.adj,PTGENDER==1)$MeanT,breaks = 15)
hist(subset(ControlNormal.adj,PTGENDER==2)$MeanT,breaks = 15)
hist(subset(ControlNormal.adj,PTGENDER==1)$MeanSAD,breaks = 15)
hist(subset(ControlNormal.adj,PTGENDER==2)$MeanSAD,breaks = 15)


#testTadploe.norm <- rankInverseNormalDataFrame(TADPOLE_predictors[prednames,], testTadploe.adj, ControlNormal.adj,strata="PTGENDER")

trainTadploe.norm <- rankInverseNormalDataFrame(TADPOLE_predictors[prednames,], trainTadploe.adj, ControlNormal.adj)
testTadploe.norm <- rankInverseNormalDataFrame(TADPOLE_predictors[prednames,], testTadploe.adj, ControlNormal.adj)

mean(testTadploe.norm$MeanT)
mean(trainTadploe.norm$MeanT)
mean(testTadploe.norm$MeanSAD)
mean(trainTadploe.norm$MeanSAD)

plot(testTadploe.norm$MeanT~testTadploe.adj$MeanT)
plot(trainTadploe.norm$MeanT~trainTadploe.adj$MeanT)
plot(testTadploe.norm$MeanSAD~testTadploe.adj$MeanSAD)
plot(trainTadploe.norm$MeanSAD~trainTadploe.adj$MeanSAD)

```


```{r spliting by visit}

VISIT_TRAINCROSSMRI <- list()
VISIT_TRAINBASIC <- list()
VISIT_TESTCROSSMRI <- list()
VISIT_TESTBASIC <- list()
i = 1;
for (j in months )
{
  VISIT_TRAINCROSSMRI[[i]] <- subset(trainTadploe.adj,trainTadploe.adj$Month==j)
#  rownames(VISIT_TRAINCROSSMRI[[i]]) <- VISIT_TRAINCROSSMRI[[i]]$RID
  VISIT_TRAINBASIC[[i]] <- subset(TRAIN_TADPOLEBASIC,TRAIN_TADPOLEBASIC$Month2==j)
#  rownames(VISIT_TRAINBASIC[[i]]) <- VISIT_TRAINBASIC[[i]]$RID
  VISIT_TESTCROSSMRI[[i]] <- subset(testTadploe.adj,testTadploe.adj$Month==j)
#  rownames(VISIT_TESTCROSSMRI[[i]]) <- VISIT_TESTCROSSMRI[[i]]$RID
  VISIT_TESTBASIC[[i]] <- subset(TEST_TADPOLEBASIC,TEST_TADPOLEBASIC$Month2==j)
#  rownames(VISIT_TESTBASIC[[i]]) <- VISIT_TESTBASIC[[i]]$RID
  i = i + 1
}
sampledcolumns <- c("RID",as.character(TADPOLE_predictors[,1]));

testLastTimePointWithNL <- subset(testTadploe.adj,LastComleteObs==1 & LastDX2=="NL")
testLastTimePointWithMCI <- subset(testTadploe.adj,LastComleteObs==1 & LastDX2=="MCI")
testLastTimePointWithAD <- subset(testTadploe.adj,LastComleteObs==1 & LastDX2=="Dementia")

testWithNL <- subset(testTadploe.adj,LastDX2=="NL")
testWithMCI <- subset(testTadploe.adj,LastDX2=="MCI")
testWithAD <- subset(testTadploe.adj,LastDX2=="Dementia")

checkIDs <- c(as.character(testLastTimePointWithNL$RID),as.character(testLastTimePointWithMCI$RID),as.character(testLastTimePointWithAD$RID))
#write.csv(checkIDs,file="TestIDsWithCO.csv")


```




```{r univariate NL to AD}
CASESNLtoAD <- NULL
yearNLtoAD <- NULL
controlYearNLtoAD <- NULL;
CONTROLNLtoAD <- NULL

basecolumns <- sampledcolumns[-c(1:7)]

tmpss <-  subset(VISIT_TRAINCROSSMRI[[1]],NL_AD==1 & BDX==1)
BLCASESNLtoAD <- tmpss[,basecolumns]
tmpss <-  subset(VISIT_TESTCROSSMRI[[1]],NL_AD==1 & BDX==1)
BLCASESNLtoAD <- rbind(BLCASESNLtoAD,tmpss[,basecolumns])

tmpss <-  subset(VISIT_TRAINCROSSMRI[[1]],BXBL=="CN" & LastDX2=="NL" & LastVisit>3)
BLCONTROLNLtoAD <- tmpss[,basecolumns]
tmpss <-  subset(VISIT_TESTCROSSMRI[[1]],BXBL=="CN" & LastDX2=="NL" & LastVisit>3)
BLCONTROLNLtoAD <- rbind(BLCONTROLNLtoAD,tmpss[,basecolumns])


for (j in 1:length(VISIT_TRAINCROSSMRI) )
{
  tmpss <-  subset(VISIT_TRAINCROSSMRI[[j]],NL_AD==1 & BDX==1)
  yearNLtoAD <- c(yearNLtoAD,(tmpss$YearNLtoAD))
  CASESNLtoAD <- rbind(CASESNLtoAD,tmpss[,sampledcolumns])
  tmpss <- subset(VISIT_TESTCROSSMRI[[j]],NL_AD==1 & BDX==1 )
  yearNLtoAD <- c(yearNLtoAD,(tmpss$YearNLtoAD))
  CASESNLtoAD <- rbind(CASESNLtoAD,tmpss[,sampledcolumns])

  tmpss <- subset(VISIT_TRAINCROSSMRI[[j]],BXBL=="CN" & LastDX2=="NL" & LastVisit>3)
  controlYearNLtoAD <- c(controlYearNLtoAD,(tmpss$YearNLtoAD))
  CONTROLNLtoAD <- rbind(CONTROLNLtoAD,tmpss[,sampledcolumns])
  tmpss <- subset(VISIT_TESTCROSSMRI[[j]],BXBL=="CN" & LastDX2=="NL" & LastVisit>3)
  controlYearNLtoAD <- c(controlYearNLtoAD,(tmpss$YearNLtoAD))
  CONTROLNLtoAD <- rbind(CONTROLNLtoAD,tmpss[,sampledcolumns])
}

CASESNLtoAD <- cbind(yearNLtoAD,CASESNLtoAD)
CASESNLtoAD <- CASESNLtoAD[complete.cases(CASESNLtoAD),]
CONTROLNLtoAD <- cbind(controlYearNLtoAD,CONTROLNLtoAD)
CONTROLNLtoAD <- CONTROLNLtoAD[complete.cases(CONTROLNLtoAD),]



NLAZUniRankFeaturesRaw <- univariateRankVariables(variableList = TADPOLE_predictors,
	                                            formula = "yearNLtoAD ~ 1",
	                                            Outcome = "yearNLtoAD",
	                                            data = CASESNLtoAD, 
	                                            categorizationType = "Raw", 
	                                            type = "LM", 
	                                            rankingTest = "Ztest",
	                                            description = "Description",
                                               uniType="Regression")

```


```{r Modeling NL to AD}

ids <- unique(as.character(CASESNLtoAD$RID))
NLtoAD <- list();
baggedformula <- character();
baggedformula2 <- character();
for (n in 1:100)
{
  singlecaseNLtoAD <- NULL;
  for (i in ids)
  {
    case1 <- subset(CASESNLtoAD,RID==i)
    caserows <- nrow(case1)
    if (caserows>1)
    {
      singlecaseNLtoAD <- rbind(singlecaseNLtoAD,case1[sample(caserows, 1),])
    }
    else
    {
      singlecaseNLtoAD <- rbind(singlecaseNLtoAD,case1)
    }
  }
  singlecaseNLtoAD$RID <- NULL;
  print(nrow(singlecaseNLtoAD))
  system.time(NLtoAD[[n]] <- FRESA.Model(yearNLtoAD ~ 1,singlecaseNLtoAD))
  if (length(NLtoAD[[n]]$bagging$bagged.model$coefficients)>1)
  {
    baggedformula <- append(baggedformula,NLtoAD[[n]]$bagging$formula)
  }
  if (length(NLtoAD[[n]]$BSWiMS.model$coefficients)>1)
  {
    baggedformula2 <- append(baggedformula2,NLtoAD[[n]]$BSWiMS.model$formula)
  }
}
save(NLtoAD,file="NLtoAD.RDATA")
mp <- medianPredict(baggedformula,CASESNLtoAD,predictType ="linear",type="LM")
plot(CASESNLtoAD$yearNLtoAD~mp$medianPredict)
cor.test(CASESNLtoAD$yearNLtoAD,mp$medianPredict)

bgmod <- baggedModel(as.character(baggedformula2),CASESNLtoAD,type="LM",univariate=NLtoAD[[1]]$univariateAnalysis)
barplot(bgmod$frequencyTable)
mpb <- medianPredict(bgmod$formula,CASESNLtoAD,predictType ="linear",type="LM")
plot(CASESNLtoAD$yearNLtoAD~mpb$medianPredict)
cor.test(CASESNLtoAD$yearNLtoAD,mpb$medianPredict)

testLastTimePointWithNL$yearNLtoAD <- numeric(nrow(testLastTimePointWithNL))
mp <- medianPredict(baggedformula,CASESNLtoAD,testLastTimePointWithNL,predictType ="linear",type="LM")
cdft <- NULL
x <- (1:60)/12
for (i in 1:nrow(mp$predictions))
{
  fn <- ecdf(as.numeric(mp$predictions[i,-1]))
  cdft <- rbind(cdft,fn(x))
}
rownames(cdft) <- rownames(mp$predictions)
write.csv(cdft,file="NLtoADTimeCDF.csv")
write.csv(mp$predictions,file="NLtoADTimePrediction.csv")

```

```{r predicting CN to AD conversion}

classNLtoAD <- CASESNLtoAD;
classNLtoAD$yearNLtoAD <- NULL
classNLtoAD$Event <- 1
cclassNLtoAD <- CONTROLNLtoAD
cclassNLtoAD$controlYearNLtoAD <- NULL
cclassNLtoAD$Event <- 0

samplecontrol <- sample(nrow(cclassNLtoAD),nrow(cclassNLtoAD)/2)
#sampletrain <- sample(nrow(classNLtoAD),4*nrow(classNLtoAD)/5)
#trainDataNLtoAD <- rbind(classNLtoAD[sampletrain,],cclassNLtoAD[samplecontrol,])
trainDataNLtoAD <- rbind(classNLtoAD,cclassNLtoAD[samplecontrol,])
testDataNLtoAD <- rbind(classNLtoAD,cclassNLtoAD[-samplecontrol,])

ids <- unique(as.character(trainDataNLtoAD$RID))
PreNLtoAD <- list();
baggedformula <- character();
baggedformula2 <- character();
for (n in 1:25)
{
  singlecaseNLtoAD <- NULL;
  for (i in ids)
  {
    case1 <- subset(trainDataNLtoAD,RID==i)
    caserows <- nrow(case1)
    if (caserows>1)
    {
      singlecaseNLtoAD <- rbind(singlecaseNLtoAD,case1[sample(caserows, 1),])
    }
    else
    {
      singlecaseNLtoAD <- rbind(singlecaseNLtoAD,case1)
    }
  }
  singlecaseNLtoAD$RID <- NULL;
  system.time(PreNLtoAD[[n]] <- FRESA.Model(Event ~ 1,singlecaseNLtoAD))
}
save(PreNLtoAD,file="LogitLNtoAD.RDATA")
for (n in 1:25)
{
  if (length(PreNLtoAD[[n]]$bagging$bagged.model$coefficients)>1)
  {
    baggedformula <- append(baggedformula,PreNLtoAD[[n]]$bagging$formula)
  }
  if (length(PreNLtoAD[[n]]$BSWiMS.model$coefficients)>1)
  {
    baggedformula2 <- append(baggedformula2,PreNLtoAD[[n]]$BSWiMS.model$formula)
  }
}
bgmod <- baggedModel(as.character(baggedformula2),trainDataNLtoAD,type="LOGIT",univariate=PreNLtoAD[[1]]$univariateAnalysis)
barplot(bgmod$frequencyTable)
mpb <- medianPredict(bgmod$formula,trainDataNLtoAD,predictType ="linear",type="LOGIT")
pm2b <- plotModels.ROC(mpb$predictions,main="Bagging",cex=0.90)

mptb <- medianPredict(bgmod$formula,trainDataNLtoAD,testDataNLtoAD,predictType ="linear",type="LOGIT")
pm2tb <- plotModels.ROC(mptb$predictions,main="Bagging",cex=0.90)

mptb <- medianPredict(bgmod$formula,trainDataNLtoAD,testDataNLtoAD,predictType ="linear",type="SVM")
mptb$predictions$V2 <- mptb$predictions$V2 -0.5
pm2tb <- plotModels.ROC(mptb$predictions,main="SVN",cex=0.90)

mp2 <- medianPredict(as.character(baggedformula2),trainDataNLtoAD,testDataNLtoAD,predictType ="linear",type="LOGIT")
pm2 <- plotModels.ROC(mp2$predictions,main="Bagging",cex=0.90)

mp3 <- medianPredict(as.character(baggedformula),trainDataNLtoAD,testDataNLtoAD,predictType ="linear",type="LOGIT")
pm3 <- plotModels.ROC(mp3$predictions,main="Bagging",cex=0.90)

mps3 <- medianPredict(as.character(baggedformula),trainDataNLtoAD,testDataNLtoAD,predictType ="linear",type="SVM")
mps3$predictions[,2:26] <- mps3$predictions[,2:26] -0.5
pms3 <- plotModels.ROC(mp3$predictions,main="SVM",cex=0.90)


testLastTimePointWithNL$Event <- rep(0,nrow(testLastTimePointWithNL))
predictionNormalsToAD <- medianPredict(as.character(baggedformula2),trainDataNLtoAD,testLastTimePointWithNL,predictType ="prob",type="LOGIT")
write.csv(predictionNormalsToAD$medianPredict,file="ADFromNormalPrediction.csv")

```



```{r univariate MCI to AD}
CASESMCItoAD <- NULL
YearMCItoAD <- NULL
controlYearMCItoAD <- NULL;
CONTROLMCItoAD <- NULL;
TestSetMCItoAD <- NULL;

for (j in 1:length(VISIT_TRAINCROSSMRI) )
{
  #Train 
  tmpss <-  subset(VISIT_TRAINCROSSMRI[[j]],MCI_AD==1 & BDX==2)
  YearMCItoAD <- c(YearMCItoAD,(tmpss$YearMCItoAD))
  CASESMCItoAD <- rbind(CASESMCItoAD,tmpss[,sampledcolumns])
  
  tmpss <- subset(VISIT_TRAINCROSSMRI[[j]],BXBL=="MCI" & LastDX2=="MCI" & LastVisit>3.0)
  controlYearMCItoAD <- c(controlYearMCItoAD,(tmpss$YearMCItoAD))
  CONTROLMCItoAD <- rbind(CONTROLMCItoAD,tmpss[,sampledcolumns])

  #Test 
  tmpss <-  subset(VISIT_TESTCROSSMRI[[j]],MCI_AD==1 & BDX==2)
  arows <- cbind(rep(1,nrow(tmpss)),tmpss$YearMCItoAD,tmpss[,sampledcolumns])
  colnames(arows) <- c("Event","YearMCItoAD",sampledcolumns)
  TestSetMCItoAD <- rbind(TestSetMCItoAD,arows)

  tmpss <-  subset(VISIT_TESTCROSSMRI[[j]],BXBL=="MCI" & LastDX2=="MCI" & LastVisit>3.0)
  arows <- cbind(rep(0,nrow(tmpss)),tmpss$YearMCItoAD,tmpss[,sampledcolumns])
  colnames(arows) <- c("Event","YearMCItoAD",sampledcolumns)
  TestSetMCItoAD <- rbind(TestSetMCItoAD,arows)

}

CASESMCItoAD <- cbind(YearMCItoAD,CASESMCItoAD)
CASESMCItoAD <- CASESMCItoAD[complete.cases(CASESMCItoAD),]
CONTROLMCItoAD <- cbind(controlYearMCItoAD,CONTROLMCItoAD)
CONTROLMCItoAD <- CONTROLMCItoAD[complete.cases(CONTROLMCItoAD),]


MCIADUniRankFeaturesRaw <- univariateRankVariables(variableList = TADPOLE_predictors,
	                                            formula = "YearMCItoAD ~ 1",
	                                            Outcome = "YearMCItoAD",
	                                            data = CASESMCItoAD, 
	                                            categorizationType = "Raw", 
	                                            type = "LM", 
	                                            rankingTest = "Ztest",
	                                            description = "Description",
                                               uniType="Regression")

```


```{r Modeling MCI to AD}

otime <- subset(TestSetMCItoAD,Event==1)
otime$Event <- NULL

timeMCItoAD <- rbind(CASESMCItoAD,otime)
ids <- unique(as.character(timeMCItoAD$RID))
sampleIDS_MCItoAD <- ids[sample(length(ids),9*length(ids)/10)]

save(sampleIDS_MCItoAD,file="sampleIDS_MCItoAD.RDATA")


trainMCItoAD <- subset(timeMCItoAD,RID %in% sampleIDS_MCItoAD)
testMCItoAD <- subset(timeMCItoAD,!(RID %in% sampleIDS_MCItoAD))

trainMCItoAD <- trainMCItoAD[complete.cases(trainMCItoAD),]
testMCItoAD <- testMCItoAD[complete.cases(testMCItoAD),]
print(length(unique(as.character(trainMCItoAD$RID))))
print(length(unique(as.character(testMCItoAD$RID))))

ids <- unique(as.character(trainMCItoAD$RID))
sys_times <- NULL;
MCItoAD <- list();
n=1
for (n in 1:50)
{
  singlecaseMCItoAD <- NULL;
  for (i in ids)
  {
    case1 <- subset(trainMCItoAD,RID==i)
    caserows <- nrow(case1)
    if (caserows>1)
    {
      singlecaseMCItoAD <- rbind(singlecaseMCItoAD,case1[sample(caserows, 1),])
    }
    else
    {
      singlecaseMCItoAD <- rbind(singlecaseMCItoAD,case1)
    }
  }
  singlecaseMCItoAD$RID <- NULL;
  singlecaseMCItoAD$BDX <- NULL;
  print(nrow(singlecaseMCItoAD))
  sys_times <- append(sys_times,system.time(MCItoAD[[n]] <- FRESA.Model(YearMCItoAD ~ 1,singlecaseMCItoAD)))
}
save(sys_times,file="sys_times_MCItoAD_50_90.RDATA")
save(MCItoAD,file="MCItoAD_50_90.RDATA")

#load(file="MCItoAD_25.RDATA")
#load(file="sampleIDS_MCItoAD.RDATA")
#trainMCItoAD <- subset(timeMCItoAD,RID %in% sampleIDS_MCItoAD)
#testMCItoAD <- subset(timeMCItoAD,!(RID %in% sampleIDS_MCItoAD))

ids <- unique(as.character(trainMCItoAD$RID))

baggedformula <- character();
baggedformula2 <- character();
for (n in 1:50)
{
  if (length(MCItoAD[[n]]$bagging$bagged.model$coefficients)>1)
  {
    baggedformula <- append(baggedformula,MCItoAD[[n]]$bagging$formula)
  }
  if (length(MCItoAD[[n]]$BSWiMS.model$coefficients)>1)
  {
    baggedformula2 <- append(baggedformula2,MCItoAD[[n]]$BSWiMS.model$formula)
  }
}

bgmod <- baggedModel(as.character(baggedformula2),trainMCItoAD,type="LM",univariate =MCItoAD[[1]]$univariateAnalysis )

mpb <- medianPredict(bgmod$formula,trainMCItoAD,testMCItoAD,type="SVM")
plot(testMCItoAD$YearMCItoAD~mpb$medianPredict)
cor.test(testMCItoAD$YearMCItoAD,mpb$medianPredict)

mpb <- medianPredict(bgmod$formula,trainMCItoAD,testMCItoAD,predictType ="linear",type="LM")
plot(testMCItoAD$YearMCItoAD~mpb$medianPredict)
cor.test(testMCItoAD$YearMCItoAD,mpb$medianPredict)

mp <- medianPredict(as.character(baggedformula),trainMCItoAD,testMCItoAD,predictType ="linear",type="LM")
plot(testMCItoAD$YearMCItoAD~mp$medianPredict)
cor.test(testMCItoAD$YearMCItoAD,mp$medianPredict)

mp <- medianPredict(as.character(baggedformula),trainMCItoAD,testMCItoAD,type="SVM")
plot(testMCItoAD$YearMCItoAD~mp$medianPredict)
cor.test(testMCItoAD$YearMCItoAD,mp$medianPredict)

mp <- medianPredict(as.character(baggedformula2),trainMCItoAD,testMCItoAD,type="SVM")
plot(testMCItoAD$YearMCItoAD~mp$medianPredict)
cor.test(testMCItoAD$YearMCItoAD,mp$medianPredict)

mp <- medianPredict(as.character(baggedformula2),trainMCItoAD,testMCItoAD,predictType ="linear",type="LM")
plot(testMCItoAD$YearMCItoAD~mp$medianPredict)
cor.test(testMCItoAD$YearMCItoAD,mp$medianPredict)

testWithMCI$yearNLtoAD <- numeric(nrow(testWithMCI))
mp <- medianPredict(as.character(baggedformula2),trainMCItoAD,testWithMCI,type="SVM")
cdft <- NULL
x <- (1:60)/12
for (i in 1:nrow(mp$predictions))
{
  fn <- ecdf(as.numeric(mp$predictions[i,-1]))
  cdft <- rbind(cdft,fn(x))
}
rownames(cdft) <- rownames(mp$predictions)
write.csv(cdft,file="MCItoADTimeCDF.csv")
write.csv(mp$predictions,file="MCItoADTimePrediction.csv")

mpl <- medianPredict(as.character(baggedformula2),trainMCItoAD,testWithMCI,predictType ="linear",type="LM")
cdft <- NULL
x <- (1:60)/12
for (i in 1:nrow(mpl$predictions))
{
  fn <- ecdf(as.numeric(mpl$predictions[i,-1]))
  cdft <- rbind(cdft,fn(x))
}
rownames(cdft) <- rownames(mpl$predictions)
write.csv(cdft,file="LMMCItoADTimeCDF.csv")
write.csv(mpl$predictions,file="LMMCItoADTimePrediction.csv")


```

```{r predicting MCI to AD conversion}

otime <- TestSetMCItoAD 

classMCItoAD <- CASESMCItoAD
classMCItoAD$Event <- 1
cclassMCItoAD <- CONTROLMCItoAD
cclassMCItoAD$Event <- 0
cclassMCItoAD$controlYearMCItoAD <- NULL
cclassMCItoAD$YearMCItoAD <- rep(100,nrow(cclassMCItoAD))

allMCItoADCases <- rbind(classMCItoAD,subset(otime,Event==1))
allMCItoADControl <- rbind(cclassMCItoAD,subset(otime,Event==0))
print(length(unique(as.character(allMCItoADCases$RID))))
print(length(unique(as.character(allMCItoADControl$RID))))

ids <- unique(as.character(allMCItoADCases$RID))
sampleCasesIDS_MCItoAD <- ids[sample(length(ids),3*length(ids)/4)]
save(sampleCasesIDS_MCItoAD,file="sampleCasesIDS_MCItoAD.RDATA")
ids <- unique(as.character(allMCItoADControl$RID))
sampleControlsIDS_MCItoAD <- ids[sample(length(ids),3*length(ids)/4)]
save(sampleControlsIDS_MCItoAD,file="sampleControlsIDS_MCItoAD.RDATA")


trainMCItoAD <- subset(timeMCItoAD,RID %in% sampleIDS_MCItoAD)
testMCItoAD <- subset(timeMCItoAD,!(RID %in% sampleIDS_MCItoAD))


trainDataMCItoAD <- rbind(subset(allMCItoADCases,RID %in% sampleCasesIDS_MCItoAD),
                          subset(allMCItoADControl,RID %in% sampleControlsIDS_MCItoAD))
testDataMCItoAD <- rbind(subset(allMCItoADCases,!(RID %in% sampleCasesIDS_MCItoAD)),
                          subset(allMCItoADControl,!(RID %in% sampleControlsIDS_MCItoAD)))

trainDataMCItoAD$YearMCItoAD <- NULL
trainDataMCItoAD$BDX <- NULL
ids <- unique(as.character(subset(allMCItoADCases,!(RID %in% sampleCasesIDS_MCItoAD))$RID))



ids <- unique(as.character(trainDataMCItoAD$RID))
preMCItoAD  <- list();
#load(file="preMCItoAD.RDATA")
n=1
for (n in 1:25)
{
  singlecaseMCItoAD <- NULL;
  for (i in ids)
  {
    case1 <- subset(trainDataMCItoAD,RID==i)
    caserows <- nrow(case1)
    if (caserows>1)
    {
      singlecaseMCItoAD <- rbind(singlecaseMCItoAD,case1[sample(caserows, 1),])
    }
    else
    {
      singlecaseMCItoAD <- rbind(singlecaseMCItoAD,case1)
    }
  }
  singlecaseMCItoAD$RID <- NULL;
  singlecaseMCItoAD$BDX <- NULL;
  print(sum(singlecaseMCItoAD$Event))
  print(sum(singlecaseMCItoAD$Event==0))
  system.time(preMCItoAD[[n]] <- FRESA.Model(Event ~ 1,singlecaseMCItoAD))
}
save(preMCItoAD,file="preMCItoAD.RDATA")

#load(file="preMCItoAD.RDATA")
#load(file="sampleMCItoADcontrol.RDATA")
#load(file="sampleMCItoADcases.RDATA")
#trainDataMCItoAD <- rbind(allMCItoADCases[sampleMCItoADcases,],allMCItoADControl[sampleMCItoADcontrol,])
#testDataMCItoAD <- rbind(allMCItoADCases[-sampleMCItoADcases,],allMCItoADControl[-sampleMCItoADcontrol,])
#ids <- unique(as.character(trainDataMCItoAD$RID))

baggedformula <- character();
baggedformula2 <- character();
for (n in 1:25)
{
  if (length(preMCItoAD[[n]]$bagging$bagged.model$coefficients)>1)
  {
    baggedformula <- append(baggedformula,preMCItoAD[[n]]$bagging$formula)
  }
  if (length(preMCItoAD[[n]]$BSWiMS.model$coefficients)>1)
  {
    baggedformula2 <- append(baggedformula2,preMCItoAD[[n]]$BSWiMS.model$formula)
  }
}

testDataMCItoAD <- testDataMCItoAD[complete.cases(testDataMCItoAD),]
bgmod <- baggedModel(as.character(baggedformula2),trainDataMCItoAD,type="LOGIT",univariate=preMCItoAD[[1]]$univariateAnalysis)
barplot(bgmod$frequencyTable)
mpb <- medianPredict(bgmod$formula,trainDataMCItoAD,testDataMCItoAD,predictType ="linear",type="LOGIT")
pm2b <- plotModels.ROC(mpb$predictions,main="Bagging",cex=0.90)

mpb <- medianPredict(bgmod$formula,trainDataMCItoAD,testDataMCItoAD,type="SVM")
mpb$predictions[-1] <- mpb$predictions[-1] - 0.5
pm2b <- plotModels.ROC(mpb$predictions,main="SVM",cex=0.90)


bgmod2 <- baggedModel(as.character(baggedformula),trainDataMCItoAD,type="LOGIT",univariate=preMCItoAD[[1]]$univariateAnalysis)
varlist <- c(all.vars(bgmod2$bagged.model$formula)[-1],all.vars(bgmod2$bagged.model$formula)[-1])
varlist <- unique(varlist)
system.time(MCItoADsig <- getSignature(data=trainDataMCItoAD,varlist=varlist,Outcome="Event",method="spearman"))

BAGGINGdistance <- signatureDistance(MCItoADsig$caseTamplate,testDataMCItoAD,"spearman") - signatureDistance(MCItoADsig$controlTemplate,testDataMCItoAD,"spearman") 

roc(as.vector(testDataMCItoAD$Event),BAGGINGdistance,plot=TRUE)

mp2 <- medianPredict(as.character(baggedformula2),trainDataMCItoAD,testDataMCItoAD,predictType ="linear",type="LOGIT")
mp2 <- medianPredict(as.character(baggedformula2),trainDataMCItoAD,testDataMCItoAD,predictType ="prob",type="LOGIT")
pm2 <- plotModels.ROC(mp2$predictions,main="Bagging",cex=0.90)

mpS2 <- medianPredict(as.character(baggedformula2),trainDataMCItoAD,testDataMCItoAD,type="SVM")
mpS2$predictions[-1] <- mpS2$predictions[-1] - 0.5
pmS2 <- plotModels.ROC(mpS2$predictions,main="SVM",cex=0.90)
plot(mp2$medianPredict~mpS2$medianPredict)

mp3 <- medianPredict(as.character(baggedformula),trainDataMCItoAD,testDataMCItoAD,predictType ="linear",type="LOGIT")
pm3 <- plotModels.ROC(mp3$predictions,main="Bagging",cex=0.90)

mps3 <- medianPredict(as.character(baggedformula),trainDataMCItoAD,testDataMCItoAD,type="SVM")
mps3$predictions[-1] <- mps3$predictions[-1] - 0.5
pms3 <- plotModels.ROC(mps3$predictions,main="SVM",cex=0.90)


testLastTimePointWithMCI$Event <- rep(0,nrow(testLastTimePointWithMCI))
predictionMCIToAD <- medianPredict(as.character(baggedformula2),trainDataMCItoAD,testLastTimePointWithMCI,predictType ="prob",type="SVM")
write.csv(predictionMCIToAD$medianPredict,file="ADFromMCIPrediction.csv")

predictionMCIToAD <- medianPredict(as.character(baggedformula2),trainDataMCItoAD,testLastTimePointWithMCI,predictType ="prob",type="LOGIT")
write.csv(predictionMCIToAD$medianPredict,file="LOGITADFromMCIPrediction.csv")


testWithMCI$Event <- rep(0,nrow(testWithMCI))
predictionAllMCIToAD <- medianPredict(as.character(baggedformula2),trainDataMCItoAD,testWithMCI,predictType ="prob",type="SVM")
logpredictionAllMCIToAD <- medianPredict(as.character(baggedformula2),trainDataMCItoAD,testWithMCI,predictType ="prob",type="LOGIT")

write.csv(predictionAllMCIToAD$medianPredict,file="ALLADFromMCIPrediction.csv")
write.csv(predictionAllMCIToAD$predictions,file="ALLPredADFromMCIPrediction.csv")

write.csv(logpredictionAllMCIToAD$medianPredict,file="LogitALLADFromMCIPrediction.csv")
write.csv(logpredictionAllMCIToAD$predictions,file="LogitALLPredADFromMCIPrediction.csv")

plot(logpredictionAllMCIToAD$medianPredict~predictionAllMCIToAD$medianPredict)


```

```{r univariate NL to MCI}
CASESNLtoMCI <- NULL
yearNLtoMCI <- NULL
controlYearNLtoMCI <- NULL;
CONTROLNLtoMCI <- NULL

tmpss <-  subset(VISIT_TRAINCROSSMRI[[1]],NL_MCI==1 & BDX==1)
BLCASESNLtoMCI <- tmpss[,sampledcolumns]
j=1
for (j in 1:length(VISIT_TRAINCROSSMRI) )
{
  tmpss <-  subset(VISIT_TRAINCROSSMRI[[j]],NL_MCI==1 & BDX==1)
  yearNLtoMCI <- c(yearNLtoMCI,(tmpss$YearNLtoMCI))
  CASESNLtoMCI <- rbind(CASESNLtoMCI,tmpss[,sampledcolumns])
  tmpss <- subset(VISIT_TESTCROSSMRI[[j]],NL_MCI==1 & BDX==1 )
  yearNLtoMCI <- c(yearNLtoMCI,(tmpss$YearNLtoMCI))
  CASESNLtoMCI <- rbind(CASESNLtoMCI,tmpss[,sampledcolumns])

  tmpss <- subset(VISIT_TRAINCROSSMRI[[j]],BXBL=="CN" & LastDX2=="NL" & LastVisit>3)
  controlYearNLtoMCI <- c(controlYearNLtoMCI,(tmpss$YearNLtoMCI))
  CONTROLNLtoMCI <- rbind(CONTROLNLtoMCI,tmpss[,sampledcolumns])
}

CASESNLtoMCI <- cbind(yearNLtoMCI,CASESNLtoMCI)
CASESNLtoMCI <- CASESNLtoMCI[complete.cases(CASESNLtoMCI),]
CONTROLNLtoMCI <- cbind(controlYearNLtoMCI,CONTROLNLtoMCI)
CONTROLNLtoMCI <- CONTROLNLtoMCI[complete.cases(CONTROLNLtoMCI),]


NLMCIUniRankFeaturesRaw <- univariateRankVariables(variableList = TADPOLE_predictors,
	                                            formula = "yearNLtoMCI ~ 1",
	                                            Outcome = "yearNLtoMCI",
	                                            data = CASESNLtoMCI, 
	                                            categorizationType = "Raw", 
	                                            type = "LM", 
	                                            rankingTest = "Ztest",
	                                            description = "Description",
                                               uniType="Regression")

```


```{r Modeling MCI to AD}
system.time(NLtoMCI <- FRESA.Model(yearNLtoMCI ~ 1,CASESNLtoMCI,equivalent=TRUE,CVfolds=5, repeats=5,pvalue=0.05,filter.p.value=0.1))

main.title <- "LASSO"
colname <- "Prediction"

boxsta <- boxplot(NLtoMCI$cvObject$LASSO.testPredictions[,colname]~rownames(NLtoMCI$cvObject$LASSO.testPredictions),las=2,cex.axis=0.6,main=paste("By ID:",main.title),ylab="Prediction",xlab="ID",plot=TRUE)
yearNLtoMCI <- CASESNLtoMCI[boxsta$names,"yearNLtoMCI"]
cor.test(yearNLtoMCI,boxsta$stats[3,],method="spearman")
plot(yearNLtoMCI,boxsta$stats[3,])
LASSOMSE <- sqrt(mean((yearNLtoMCI-boxsta$stats[3,])^2))

main.title <- "B:SWIMS"
colname <- "Prediction"

boxsta <- boxplot(NLtoMCI$cvObject$Models.testPrediction[,colname]~rownames(NLtoMCI$cvObject$Models.testPrediction),las=2,cex.axis=0.6,main=paste("By ID:",main.title),ylab="Prediction",xlab="ID",plot=TRUE)
yearNLtoMCI <- CASESNLtoMCI[boxsta$names,"yearNLtoMCI"]
cor.test(yearNLtoMCI,boxsta$stats[3,],method="spearman")
plot(yearNLtoMCI,boxsta$stats[3,])
BSWIMSMSE <- sqrt(mean((yearNLtoMCI-boxsta$stats[3,])^2))

main.title <- "Ensemble B:SWIMS"
colname <- "Median"

boxsta <- boxplot(NLtoMCI$cvObject$Models.testPrediction[,colname]~rownames(NLtoMCI$cvObject$Models.testPrediction),las=2,cex.axis=0.6,main=paste("By ID:",main.title),ylab="Prediction",xlab="ID",plot=TRUE)
yearNLtoMCI <- CASESNLtoMCI[boxsta$names,"yearNLtoMCI"]
cor.test(yearNLtoMCI,boxsta$stats[3,],method="spearman")
plot(yearNLtoMCI,boxsta$stats[3,])
EnBSWIMSMSE <- sqrt(mean((yearNLtoMCI-boxsta$stats[3,])^2))

main.title <- "Bagging B:SWIMS"
colname <- "Bagged"

boxsta <- boxplot(NLtoMCI$cvObject$Models.testPrediction[,colname]~rownames(NLtoMCI$cvObject$Models.testPrediction),las=2,cex.axis=0.6,main=paste("By ID:",main.title),ylab="Prediction",xlab="ID",plot=TRUE)
yearNLtoMCI <- CASESNLtoMCI[boxsta$names,"yearNLtoMCI"]
cor.test(yearNLtoMCI,boxsta$stats[3,],method="spearman")
plot(yearNLtoMCI,boxsta$stats[3,])
BaBSWIMSMSE <- sqrt(mean((yearNLtoMCI-boxsta$stats[3,])^2))

main.title <- "Equivalent B:SWIMS"
colname <- "Equivalent"

boxsta <- boxplot(NLtoMCI$cvObject$Models.testPrediction[,colname]~rownames(NLtoMCI$cvObject$Models.testPrediction),las=2,cex.axis=0.6,main=paste("By ID:",main.title),ylab="Prediction",xlab="ID",plot=TRUE)
yearNLtoMCI <- CASESNLtoMCI[boxsta$names,"yearNLtoMCI"]
cor.test(yearNLtoMCI,boxsta$stats[3,],method="spearman")
plot(yearNLtoMCI,boxsta$stats[3,])
EqBSWIMSMSE <- sqrt(mean((yearNLtoMCI-boxsta$stats[3,])^2))


```

```{r predicting MCI to AD conversion}

CASESNLtoMCI$yearNLtoMCI <- NULL
CASESNLtoMCI$Event <- 1
CONTROLNLtoMCI$controlYearNLtoMCI <- NULL
CONTROLNLtoMCI$Event <- 0

trainDataNLtoMCI <- rbind(CASESNLtoMCI,CONTROLNLtoMCI)

system.time(preNLtoMCI <- FRESA.Model(Event ~ 1,trainDataNLtoMCI,CVfolds=5, repeats=3,filter.p.value=0.05,pvalue=0.05, usrFitFun= svm))

pm <- plotModels.ROC(preNLtoMCI$cvObject$LASSO.testPredictions,theCVfolds=3,main="CV LASSO",cex=0.90)
pm <- plotModels.ROC(preNLtoMCI$cvObject$KNN.testPrediction,theCVfolds=3,main="KNN",cex=0.90)
pm <- plotModels.ROC(preNLtoMCI$cvObject$Models.testPrediction,theCVfolds=3,predictor="Prediction",main="BB:SWiMS",cex=0.90)
pm <- plotModels.ROC(preNLtoMCI$cvObject$Models.testPrediction,theCVfolds=3,predictor="Median",main="Forward Median",cex=0.90)
pm <- plotModels.ROC(preNLtoMCI$cvObject$Models.testPrediction,theCVfolds=3,predictor="usrFitFunction_Sel",main="SVM",cex=0.90)


```

