---
title: "TADPOLE"
author: "José Tamez-Peña"
date: "October 20, 2017"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r, echo = FALSE}
knitr::opts_chunk$set(collapse = TRUE, warning = FALSE, message = FALSE,comment = "#>")
```

```{r Libraries, echo = FALSE}

library("epiR")
library("FRESA.CAD")
library(network)
library(GGally)
library("e1071")

TADPOLE_predictors <- read.delim("PredictorsList.txt")

load(file="D3Imputed.RDATA")
load(file="TEST_TADPOLEMRI.RDATA")
load(file="TRAIN_TADPOLEMRI.RDATA")
load(file="trainTadploe.norm.RDATA")
load(file="testTadploe.norm.RDATA")
load(file="D3.norm.RDATA")

```

```{r spliting by visit}
months <- c(0,3,6,12,18,24,30,36,42,48,54,60,66,72,78,84,90,96,102,108,114,120)

VISIT_TRAINCROSSMRI <- list()
VISIT_TESTCROSSMRI <- list()
i = 1;
for (j in months )
{
  VISIT_TRAINCROSSMRI[[i]] <- subset(trainTadploe.norm,Month==j)
  VISIT_TESTCROSSMRI[[i]] <- subset(testTadploe.norm,Month==j)
  i = i + 1
}
sampledcolumns <- c("RID",as.character(TADPOLE_predictors[,1]));

testLastTimePointWithNL <- subset(testTadploe.norm,LastCompleteObs==1 & LastDX2=="NL")[,sampledcolumns]
testLastTimePointWithMCI <- subset(testTadploe.norm,LastCompleteObs==1 & LastDX2=="MCI")[,sampledcolumns]
testLastTimePointWithAD <- subset(testTadploe.norm,LastCompleteObs==1 & LastDX2=="Dementia")[,sampledcolumns]

testWithNL <- subset(testTadploe.norm,LastDX2=="NL")[,sampledcolumns]
testWithMCI <- subset(testTadploe.norm,LastDX2=="MCI")[,sampledcolumns]
testWithAD <- subset(testTadploe.norm,LastDX2=="Dementia")[,sampledcolumns]

```


```{r univariate MCI to AD}
CASESMCItoAD <- NULL
YearMCItoAD <- NULL
controlYearMCItoAD <- NULL;
CONTROLMCItoAD <- NULL;
TestSetMCItoAD <- NULL;
j=1
for (j in 1:length(VISIT_TRAINCROSSMRI) )
{
  tmpss <-  subset(VISIT_TRAINCROSSMRI[[j]],MCI_AD==1 & BDX==2 & LastDX2=="Dementia")
  YearMCItoAD <- c(YearMCItoAD,as.numeric(tmpss$YearMCItoAD))
  CASESMCItoAD <- rbind(CASESMCItoAD,tmpss[,sampledcolumns])

  tmpss <- subset(VISIT_TRAINCROSSMRI[[j]],BXBL=="MCI" & LastDX2=="MCI" & LastVisit>4.0)
  controlYearMCItoAD <- c(controlYearMCItoAD,(tmpss$YearMCItoAD))
  CONTROLMCItoAD <- rbind(CONTROLMCItoAD,tmpss[,sampledcolumns])
}

CASESMCItoAD <- cbind(YearMCItoAD,CASESMCItoAD)
CASESMCItoAD <- CASESMCItoAD[complete.cases(CASESMCItoAD),]
CONTROLMCItoAD <- cbind(controlYearMCItoAD,CONTROLMCItoAD)
CONTROLMCItoAD <- CONTROLMCItoAD[complete.cases(CONTROLMCItoAD),]
colnames(CONTROLMCItoAD) <- colnames(CASESMCItoAD)



MCIADUniRankFeaturesRaw <- univariateRankVariables(variableList = TADPOLE_predictors,
	                                            formula = "YearMCItoAD ~ 1",
	                                            Outcome = "YearMCItoAD",
	                                            data = CASESMCItoAD, 
	                                            categorizationType = "Raw", 
	                                            type = "LM", 
	                                            rankingTest = "Ztest",
	                                            description = "Description",
                                               uniType="Regression")


CASESNLtoAD <- NULL
YearNLtoAD <- NULL
for (j in 1:length(VISIT_TRAINCROSSMRI) )
{
  tmpss <-  subset(VISIT_TRAINCROSSMRI[[j]],NL_AD==1 & BDX==1 & LastDX2=="Dementia")
  YearNLtoAD <- c(YearNLtoAD,(tmpss$YearNLtoAD))
  CASESNLtoAD <- rbind(CASESNLtoAD,tmpss[,sampledcolumns])
}

CasesTimetoAD <- cbind(YearNLtoAD,CASESNLtoAD)
colnames(CasesTimetoAD) <- c("theTimeToAD",colnames(CasesTimetoAD)[-1])
colnames(CASESMCItoAD) <- colnames(CasesTimetoAD)
CasesTimetoAD <- rbind(CasesTimetoAD,CASESMCItoAD)
CasesTimetoAD <- CasesTimetoAD[complete.cases(CasesTimetoAD),]
CasesTimetoAD$theTimeToAD <- sqrt(abs(CasesTimetoAD$theTimeToAD))


ToADTIme <- univariateRankVariables(variableList = TADPOLE_predictors,
	                                            formula = "theTimeToAD ~ 1",
	                                            Outcome = "theTimeToAD",
	                                            data = CasesTimetoAD, 
	                                            categorizationType = "Raw", 
	                                            type = "LM", 
	                                            rankingTest = "Ztest",
	                                            description = "Description",
                                               uniType="Regression")
```


```{r Modeling time to AD}
compute = FALSE
numberofRepp = 5
numberofFolds = 5
numberOfTrials = 5
allformulas <- character();
logitcor <- numeric();
logitMAD <- numeric();

testWithMCI$theTimeToAD <- numeric(nrow(testWithMCI))
alltestpredicts <- NULL
allD3predicts <- NULL

for ( repp in 1:numberofRepp)
{

  ids_ca <- unique(as.character(CasesTimetoAD$RID))
	casefolds <- cvTools::cvFolds(length(ids_ca), numberofFolds,1, "random");
	
	 j=1
	for (j in 1:numberofFolds)
	{

	  sampleIDS_TimeToAD <- ids_ca[casefolds$subsets[casefolds$which != j,]];

    trainTimeToAD <- subset(CasesTimetoAD,RID %in% sampleIDS_TimeToAD)
    testTimeToAD <- subset(CasesTimetoAD,!(RID %in% sampleIDS_TimeToAD))
    
    testD3 <- subset(D3.norm,!(RID %in% sampleIDS_TimeToAD))
    testD3$theTimeToAD <- rep(0,nrow(testD3))
    
    print(length(unique(as.character(trainTimeToAD$RID))))
    print(length(unique(as.character(testTimeToAD$RID))))
    
    ids <- unique(as.character(trainTimeToAD$RID))
    sys_times <- NULL;
    TimeToAD <- list();
    n=1
    if (compute)
    {
      for (n in 1:numberOfTrials)
      {
        singlecaseTimeToAD <- NULL;
        for (i in ids)
        {
          case1 <- subset(trainTimeToAD,RID==i)
          caserows <- nrow(case1)
          if (caserows>1)
          {
            singlecaseTimeToAD <- rbind(singlecaseTimeToAD,case1[sample(caserows, 1),])
          }
          else
          {
            singlecaseTimeToAD <- rbind(singlecaseTimeToAD,case1)
          }
        }
        singlecaseTimeToAD$RID <- NULL;
        singlecaseTimeToAD$BDX <- NULL;
        print(nrow(singlecaseTimeToAD))
        sys_times <- rbind(sys_times,system.time(TimeToAD[[n]] <- FRESA.Model(theTimeToAD ~ 1,singlecaseTimeToAD)))
      }
      save(sys_times,file=paste("sys_times_TimeToAD3",numberOfTrials,j,repp,".RDATA",sep="_"))
      save(TimeToAD,file=paste("TimeToAD",numberOfTrials,j,repp,".RDATA",sep="_"))
    }
    else
    {
      load(file=paste("TimeToAD",numberOfTrials,j,repp,".RDATA",sep="_"))
      sampleIDS_TimeToAD <- NULL;
    }
    
    baggedformula <- character();
    for (n in 1:numberOfTrials)
    {
      if (length(TimeToAD[[n]]$BSWiMS.model$coefficients)>1)
      {
        baggedformula <- append(baggedformula,TimeToAD[[n]]$BSWiMS.model$formula)
      }
      if (!compute)
      {
    	  idst <- unlist(str_split(rownames(TimeToAD[[n]]$bootstrappedModel$data),"_"))
        sampleIDS_TimeToAD <- append(sampleIDS_TimeToAD,idst[2*(0:(length(idst)-1))+1])
      }
    }
    
    if (!compute)
    {
    	sampleIDS_TimeToAD <- unique(sampleIDS_TimeToAD)
      trainTimeToAD <- subset(CasesTimetoAD,(RID %in% sampleIDS_TimeToAD))
      testTimeToAD <- subset(CasesTimetoAD,!(RID %in% sampleIDS_TimeToAD))
      
      testD3 <- subset(D3.norm,!(RID %in% sampleIDS_TimeToAD))
      testD3$theTimeToAD <- rep(0,nrow(testD3))
    }

    mp <- medianPredict(as.character(baggedformula),trainTimeToAD,testTimeToAD,predictType ="linear",type="LM")
    alltestpredicts <- rbind(alltestpredicts,cbind(testTimeToAD$theTimeToAD,mp$medianPredict))
    plot(testTimeToAD$theTimeToAD~mp$medianPredict)
    ct <- cor.test(testTimeToAD$theTimeToAD,mp$medianPredict)
    logitcor <- append(logitcor,ct$estimate)
    res <- testTimeToAD$theTimeToAD^2-mp$medianPredict^2
    res <- res[testTimeToAD$theTimeToAD<2]
    logitMAD <- append(logitMAD,mean(abs(res)))
    print(logitMAD)
    allformulas <- append(allformulas,as.character(baggedformula))

    mpD3 <- medianPredict(as.character(baggedformula),trainTimeToAD,testD3,predictType ="linear",type="LM")
    allD3predicts <- rbind(allD3predicts,cbind(testD3$RID,mpD3$medianPredict))

    
  }
}

plot(alltestpredicts[,1]~alltestpredicts[,2],main="All Tests")
tsamples <- length(allformulas)

mpl <- medianPredict(allformulas,CasesTimetoAD,testWithMCI,predictType ="linear",type="LM")
mpl$predictions[,-1] <- mpl$predictions[,-1]^2
cdft <- NULL
sd(mpl$predictions[30,-1])
nelem <- nrow(mpl$predictions[,-1])*ncol(mpl$predictions[,-1])

mpl$predictions[,-1] <-  mpl$predictions[,-1]+as.data.frame(matrix(rnorm(nelem,0,mean(logitMAD)),nrow=nrow(mpl$predictions)));
sd(mpl$predictions[30,-1])
to2018 <- testTadploe.norm[rownames(mpl$predictions),"to2018"]
names(to2018) <- rownames(mpl$predictions)

for (i in 1:nrow(mpl$predictions))
{
  nd <- mpl$predictions[i,-1]
  if ((sna <- sum(is.na(nd))) > 0)
  {
    if (sna > tsamples/2)
    {
      nd <- numeric(tsamples) 
    }
    else
    {
      nd <- nd[!is.na(nd)];
    }
  }
  fn <- ecdf(as.numeric(nd))
  x <- (1:60)/12+to2018[i]
  cdft <- rbind(cdft,fn(x))
}
rownames(cdft) <- rownames(mpl$predictions)
write.csv(cdft,file=paste(repp,"TimeToAD_CDF.csv",sep="_"))
write.csv(mpl$predictions,file=paste(repp,"TimeToAD.csv",sep="_"))
write.csv(allformulas,file=paste(repp,"AllFormulasTimeToAD.csv",sep="_"))

MCIandNL <- rbind(testLastTimePointWithMCI,testLastTimePointWithNL)
MCIandNL$theTimeToAD <- numeric(nrow(MCIandNL))

mpl <- medianPredict(allformulas,CasesTimetoAD,MCIandNL,predictType ="linear",type="LM")
mpl$predictions[,-1] <- mpl$predictions[,-1]^2
cdft <- NULL
sd(mpl$predictions[10,-1])
nelem <- nrow(mpl$predictions[,-1])*ncol(mpl$predictions[,-1])

mpl$predictions[,-1] <-  mpl$predictions[,-1]+as.data.frame(matrix(rnorm(nelem,0,mean(logitMAD)),nrow=nrow(mpl$predictions)));
sd(mpl$predictions[10,-1])
sum(is.na(mpl$predictions[,-1]))

to2018 <- testTadploe.norm[rownames(mpl$predictions),"to2018"]
names(to2018) <- rownames(mpl$predictions)

for (i in 1:nrow(mpl$predictions))
{
  nd <- mpl$predictions[i,-1]
  if ((sna <- sum(is.na(nd))) > 0)
  {
    if (sna > tsamples/2)
    {
      nd <- numeric(tsamples) 
    }
    else
    {
      nd <- nd[!is.na(nd)];
    }
  }
  fn <- ecdf(as.numeric(nd))
  x <- (1:60)/12+to2018[i]
  fn <- cbind(rep(names(to2018[i]),60),fn(x))
  cdft <- rbind(cdft,fn)
}
#rownames(cdft) <- rownames(mpl$predictions)
write.csv(cdft,file=paste(repp,"LastObservation_TimeToAD_CDF_C.csv",sep="_"))
write.csv(mpl$predictions,file=paste(repp,"LastObservation_TimeToAD.csv",sep="_"))


barplot(logitcor)
barplot(logitMAD)


bp <- boxplot(allD3predicts[,2]~allD3predicts[,1])
cdft <- NULL
to2018 <- D3.norm$to2018
names(to2018) <- rownames(D3.norm)
allD3predicts <- as.data.frame(allD3predicts)
i=1
tsamples <-5
for (i in 1:nrow(D3.norm))
{
  nd <- subset(allD3predicts,V1==D3.norm$RID[i])[,2];
  nd <- nd + rnorm(length(nd),0,mean(logitMAD))
  if ((sna <- sum(is.na(nd))) > 0)
  {
    if (sna > tsamples/2)
    {
      nd <- numeric(tsamples) 
    }
    else
    {
      nd <- nd[!is.na(nd)];
    }
  }
  fn <- ecdf(as.numeric(nd))
  x <- (1:60)/12+to2018[i]
  fn <- cbind(rep(names(to2018[i]),60),fn(x))
  cdft <- rbind(cdft,fn)
#  cdft <- rbind(cdft,fn(x))
}
#rownames(cdft) <- rownames(D3.norm)
write.csv(cdft,file=paste(repp,"D3_TimeToAD_CDF.csv",sep="_"))


```
