---
title: "TADPOLE"
author: "José Tamez-Peña"
date: "October 20, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r, echo = FALSE}
knitr::opts_chunk$set(collapse = TRUE, warning = FALSE, message = FALSE,comment = "#>")
```

```{r Libraries, echo = FALSE}

library("epiR")
library("FRESA.CAD")
library(network)
library(GGally)
library("e1071")

TADPOLE_BASIC <- read.delim("AllSubjectsWithBasicInfo.txt")
TADPOLE_CROSSMRI <- read.delim("CompleMRIObs.txt",na.strings = c("NA","","#DIV/0!"))
TADPOLE_predictors <- read.delim("PredictorsList.txt")
rownames(TADPOLE_BASIC) <- as.character(TADPOLE_BASIC$IDTIME)
rownames(TADPOLE_CROSSMRI) <- as.character(TADPOLE_CROSSMRI$ID_TP)


```



```{r subsets}
months <- c(0,3,6,12,18,24,30,36,42,48,54,60,66,72,78,84,90,96,102,108,114,120)


TRAIN_TADPOLEMRI <- subset(TADPOLE_CROSSMRI,TADPOLE_CROSSMRI$D1==1)
TRAIN_TADPOLEBASIC <- subset(TADPOLE_BASIC,TADPOLE_BASIC$D1==1)

```



```{r imputescoreData}
toimputeNA <- c("RID","APOE4","CDRSB","ADAS11","ADAS13","MMSE","RAVLT_immediate","RAVLT_learning","RAVLT_forgetting","RAVLT_perc_forgetting","FAQ")
basictoImpute <- TADPOLE_BASIC[,toimputeNA]
rownames(basictoImpute) <- TADPOLE_BASIC$IDTIME
ids <- unique(basictoImpute$RID)
print(sum(is.na(basictoImpute)))
for (id in ids)
{
  setid <- subset(basictoImpute,RID==id)
  setrows <- nrow(setid)
#  print(id)
  if (setrows>1)
  {
    for (var in toimputeNA[-1])
    {
      if (is.na(setid[1,var]))
      {
        setid[1,var] <- setid[2,var];
      }
      for (n in 2:setrows)
      {
        if (n<setrows)
        {
         if (is.na(setid[n,var]))
         {
           mv <- mean(c(setid[n-1,var],setid[n+1,var]),na.rm=TRUE)
           if (length(mv)>0)
           {
            setid[n,var] <- mv
           }
         }
        }
        else
        {
         if (is.na(setid[n,var]))
         {
            setid[n,var] <- setid[n-1,var]
         }
        }
      }
    }
  }
  basictoImpute[rownames(setid),] <- setid
#  print(setid)
}
print(sum(is.na(basictoImpute)))
rownames(TADPOLE_CROSSMRI) <- TADPOLE_CROSSMRI$ID_TP

TADPOLE_CROSSMRI[,toimputeNA[-1]] <- basictoImpute[rownames(TADPOLE_CROSSMRI),toimputeNA[-1]]


toimputeNA <- c("RID","Ventricle_ICV","ICV")
basictoImpute <- TADPOLE_CROSSMRI[,toimputeNA]
rownames(basictoImpute) <- TADPOLE_CROSSMRI$ID_TP
ids <- unique(basictoImpute$RID)
print(sum(is.na(basictoImpute)))
for (id in ids)
{
  setid <- subset(basictoImpute,RID==id)
  setrows <- nrow(setid)
#  print(id)
  if (setrows>1)
  {
    for (var in toimputeNA[-1])
    {
      if (is.na(setid[1,var]))
      {
        setid[1,var] <- setid[2,var];
      }
      for (n in 2:setrows)
      {
        if (n<setrows)
        {
         if (is.na(setid[n,var]))
         {
           mv <- mean(c(setid[n-1,var],setid[n+1,var]),na.rm=TRUE)
           if (length(mv)>0)
           {
            setid[n,var] <- mv
           }
         }
        }
        else
        {
         if (is.na(setid[n,var]))
         {
            setid[n,var] <- setid[n-1,var]
         }
        }
      }
    }
  }
  basictoImpute[rownames(setid),] <- setid
#  print(setid)
}
print(sum(is.na(basictoImpute)))
TADPOLE_CROSSMRI[,toimputeNA[-1]] <- basictoImpute[rownames(TADPOLE_CROSSMRI),toimputeNA[-1]]
print(sum(is.na(TADPOLE_CROSSMRI)))

```

```{r the test subsets with imputed data}
TEST_TADPOLEMRI <- subset(TADPOLE_CROSSMRI,TADPOLE_CROSSMRI$D2==1)
TEST_TADPOLEBASIC <- subset(TADPOLE_BASIC,TADPOLE_BASIC$D2==1)

```



```{r Adjusting for age and ICV}


TRAIN_TADPOLEMRI$cICV <- TRAIN_TADPOLEMRI$ICV^(1/3)
TEST_TADPOLEMRI$cICV <- TEST_TADPOLEMRI$ICV^(1/3)

rownames(TADPOLE_predictors) <- as.character(TADPOLE_predictors[,1])
prednames <- as.character(TADPOLE_predictors[-c(1:17),1])

TRAIN_TADPOLEMRI <- TRAIN_TADPOLEMRI[complete.cases(TRAIN_TADPOLEMRI[,prednames]),]
ControlNormal <- subset(TRAIN_TADPOLEMRI,BXBL=="CN" & LastDX2=="NL" & LastVisit>2 & Month==0)
sum(ControlNormal$PTGENDER==1)
sum(ControlNormal$PTGENDER==2)
hist(ControlNormal$MeanT)
hist(subset(ControlNormal,PTGENDER==1)$MeanT)
hist(subset(ControlNormal,PTGENDER==2)$MeanT)

trainTadploe.adj <- featureAdjustment(TADPOLE_predictors[prednames,], baseModel="1+AGE+cICV",data=TRAIN_TADPOLEMRI,referenceframe=ControlNormal,strata="PTGENDER", type = "LM", pvalue = 0.001)

testTadploe.adj <- featureAdjustment(TADPOLE_predictors[prednames,], baseModel="1+AGE+cICV",data=TEST_TADPOLEMRI,referenceframe=ControlNormal,strata="PTGENDER", type = "LM", pvalue = 0.001)

ControlNormal.adj <- featureAdjustment(TADPOLE_predictors[prednames,], baseModel="1+AGE+cICV",data=ControlNormal,referenceframe=ControlNormal,strata="PTGENDER", type = "LM", pvalue = 0.001)


hist(subset(ControlNormal.adj,PTGENDER==1)$MeanT,breaks = 15)
hist(subset(ControlNormal.adj,PTGENDER==2)$MeanT,breaks = 15)
hist(subset(ControlNormal.adj,PTGENDER==1)$MeanSAD,breaks = 15)
hist(subset(ControlNormal.adj,PTGENDER==2)$MeanSAD,breaks = 15)


#testTadploe.norm <- rankInverseNormalDataFrame(TADPOLE_predictors[prednames,], testTadploe.adj, ControlNormal.adj,strata="PTGENDER")

trainTadploe.norm <- rankInverseNormalDataFrame(TADPOLE_predictors[prednames,], trainTadploe.adj, ControlNormal.adj,strata="PTGENDER")
testTadploe.norm <- rankInverseNormalDataFrame(TADPOLE_predictors[prednames,], testTadploe.adj, ControlNormal.adj,strata="PTGENDER")

mean(testTadploe.norm$MeanT)
mean(trainTadploe.norm$MeanT)
mean(testTadploe.norm$MeanSAD)
mean(trainTadploe.norm$MeanSAD)

plot(testTadploe.norm$MeanT~testTadploe.adj$MeanT)
plot(trainTadploe.norm$MeanT~trainTadploe.adj$MeanT)
plot(testTadploe.norm$MeanSAD~testTadploe.adj$MeanSAD)
plot(trainTadploe.norm$MeanSAD~trainTadploe.adj$MeanSAD)

```


```{r spliting by visit}

VISIT_TRAINCROSSMRI <- list()
VISIT_TRAINBASIC <- list()
VISIT_TESTCROSSMRI <- list()
VISIT_TESTBASIC <- list()
i = 1;
for (j in months )
{
  VISIT_TRAINCROSSMRI[[i]] <- subset(trainTadploe.norm,Month==j)
  VISIT_TRAINBASIC[[i]] <- subset(TRAIN_TADPOLEBASIC,Month2==j)
  VISIT_TESTCROSSMRI[[i]] <- subset(testTadploe.norm,Month==j)
  VISIT_TESTBASIC[[i]] <- subset(TEST_TADPOLEBASIC,Month2==j)
  i = i + 1
}

sampledcolumns <- c("RID",as.character(TADPOLE_predictors[,1]));

testLastTimePointWithNL <- subset(testTadploe.norm,LastCompleteObs==1 & LastDX2=="NL")[,sampledcolumns]
testLastTimePointWithMCI <- subset(testTadploe.norm,LastCompleteObs==1 & LastDX2=="MCI")[,sampledcolumns]
testLastTimePointWithAD <- subset(testTadploe.norm,LastCompleteObs==1 & LastDX2=="Dementia")[,sampledcolumns]

testWithNL <- subset(testTadploe.norm,LastDX2=="NL")[,sampledcolumns]
testWithMCI <- subset(testTadploe.norm,LastDX2=="MCI")[,sampledcolumns]
testWithAD <- subset(testTadploe.norm,LastDX2=="Dementia")[,sampledcolumns]

checkIDs <- c(as.character(testLastTimePointWithNL$RID),as.character(testLastTimePointWithMCI$RID),as.character(testLastTimePointWithAD$RID))
#write.csv(checkIDs,file="TestIDsWithCO.csv")


```

```{r univariate NL to MCI}
CASESNLtoMCI <- NULL
YearNLtoMCI <- NULL
controlYearNLtoMCI <- NULL;
CONTROLNLtoMCI <- NULL;
j=1
for (j in 1:length(VISIT_TRAINCROSSMRI) )
{
  tmpss <-  subset(VISIT_TRAINCROSSMRI[[j]],NL_MCI==1 & BDX==1)
  YearNLtoMCI <- c(YearNLtoMCI,as.numeric(tmpss$YearNLtoMCI))
  CASESNLtoMCI <- rbind(CASESNLtoMCI,tmpss[,sampledcolumns])

  tmpss <- subset(VISIT_TRAINCROSSMRI[[j]],BXBL=="CN" & LastDX2=="NL" & LastVisit>4.0)
  controlYearNLtoMCI <- c(controlYearNLtoMCI,(tmpss$YearNLtoMCI))
  CONTROLNLtoMCI <- rbind(CONTROLNLtoMCI,tmpss[,sampledcolumns])
}

CASESNLtoMCI <- cbind(YearNLtoMCI,CASESNLtoMCI)
CASESNLtoMCI <- CASESNLtoMCI[complete.cases(CASESNLtoMCI),]
CONTROLNLtoMCI <- cbind(controlYearNLtoMCI,CONTROLNLtoMCI)
CONTROLNLtoMCI <- CONTROLNLtoMCI[complete.cases(CONTROLNLtoMCI),]
colnames(CONTROLNLtoMCI) <- colnames(CASESNLtoMCI)
CASESNLtoMCI$YearNLtoMCI <- sqrt(CASESNLtoMCI$YearNLtoMCI)


NLMCIUniRankFeaturesRaw <- univariateRankVariables(variableList = TADPOLE_predictors,
	                                            formula = "YearNLtoMCI ~ 1",
	                                            Outcome = "YearNLtoMCI",
	                                            data = CASESNLtoMCI, 
	                                            categorizationType = "Raw", 
	                                            type = "LM", 
	                                            rankingTest = "Ztest",
	                                            description = "Description",
                                               uniType="Regression")


```


```{r Modeling time to MCI}

numberofRepp=11
numberOfTrials=9
allformulas <- character();
logitcor <- numeric();
svmcor <- numeric();
svmMAD <- numeric();
logitMAD <- numeric();
baggMAD <- numeric();
tsamples <- numberofRepp*numberOfTrials

testWithNL$YearNLtoMCI <- numeric(nrow(testWithNL))
alltestpredicts <- NULL
for ( repp in 1:numberofRepp)
{

  ids <- unique(as.character(CASESNLtoMCI$RID))
  sampleIDS_TimetoMCI <- ids[sample(length(ids),9*length(ids)/10)]
  save(sampleIDS_TimetoMCI,file=paste("sampleIDS_TimetoMCI",numberOfTrials,repp,".RDATA",sep="_"))
  
  trainTimetoMCI <- subset(CASESNLtoMCI,RID %in% sampleIDS_TimetoMCI)
  testTimetoMCI <- subset(CASESNLtoMCI,!(RID %in% sampleIDS_TimetoMCI))
  
  print(length(unique(as.character(trainTimetoMCI$RID))))
  print(length(unique(as.character(testTimetoMCI$RID))))
  
  ids <- unique(as.character(trainTimetoMCI$RID))
  sys_times <- NULL;
  TimetoMCI <- list();
  n=1
  
  for (n in 1:numberOfTrials)
  {
    singlecaseTimetoMCI <- NULL;
    for (i in ids)
    {
      case1 <- subset(trainTimetoMCI,RID==i)
      caserows <- nrow(case1)
      if (caserows>1)
      {
        singlecaseTimetoMCI <- rbind(singlecaseTimetoMCI,case1[sample(caserows, 1),])
      }
      else
      {
        singlecaseTimetoMCI <- rbind(singlecaseTimetoMCI,case1)
      }
    }
    singlecaseTimetoMCI$RID <- NULL;
    singlecaseTimetoMCI$BDX <- NULL;
    print(nrow(singlecaseTimetoMCI))
    sys_times <- rbind(sys_times,system.time(TimetoMCI[[n]] <- FRESA.Model(YearNLtoMCI ~ 1,singlecaseTimetoMCI)))
  }
  save(sys_times,file=paste("sys_times_TimetoMCI3",numberOfTrials,repp,".RDATA",sep="_"))
  save(TimetoMCI,file=paste("TimetoMCI3",numberOfTrials,repp,".RDATA",sep="_"))
  
  #load(file=paste("TimetoMCI",numberOfTrials,repp,".RDATA",sep="_"))
  #load(file=paste("sampleIDS_TimetoMCI",numberOfTrials,repp,".RDATA",sep="_"))
  #trainTimetoMCI <- subset(CASESNLtoMCI,RID %in% sampleIDS_TimetoMCI)
  #testTimetoMCI <- subset(CASESNLtoMCI,!(RID %in% sampleIDS_TimetoMCI))
  #trainTimetoMCI <- trainTimetoMCI[complete.cases(trainTimetoMCI),]
  #trainTimetoMCI$YearNLtoMCI <- log(trainTimetoMCI$YearNLtoMCI+1)
  #testTimetoMCI <- testTimetoMCI[complete.cases(testTimetoMCI),]
  #testTimetoMCI$YearNLtoMCI <- log(testTimetoMCI$YearNLtoMCI+1)
  
  baggedformula <- character();
  baggedformula2 <- character();
  for (n in 1:numberOfTrials)
  {
    if (length(TimetoMCI[[n]]$bagging$bagged.model$coefficients)>1)
    {
      baggedformula <- append(baggedformula,TimetoMCI[[n]]$bagging$formula)
    }
    if (length(TimetoMCI[[n]]$BSWiMS.model$coefficients)>1)
    {
      baggedformula2 <- append(baggedformula2,TimetoMCI[[n]]$BSWiMS.model$formula)
    }
  }
  
  mp <- medianPredict(as.character(baggedformula2),trainTimetoMCI,testTimetoMCI,type="SVM")
  plot(testTimetoMCI$YearNLtoMCI~mp$medianPredict)
  ct <- cor.test(testTimetoMCI$YearNLtoMCI,mp$medianPredict)
  svmcor <- append(svmcor,ct$estimate)
  res <- testTimetoMCI$YearNLtoMCI^2-mp$medianPredict^2
  res <- res[testTimetoMCI$YearNLtoMCI<1.4]
  svmMAD <- append(svmMAD,mean(abs(res)))

  mp <- medianPredict(as.character(baggedformula2),trainTimetoMCI,testTimetoMCI,predictType ="linear",type="LM")
  alltestpredicts <- rbind(alltestpredicts,cbind(testTimetoMCI$YearNLtoMCI,mp$medianPredict))
  plot(testTimetoMCI$YearNLtoMCI~mp$medianPredict)
  ct <- cor.test(testTimetoMCI$YearNLtoMCI,mp$medianPredict)
  logitcor <- append(logitcor,ct$estimate)
  res <- testTimetoMCI$YearNLtoMCI^2-mp$medianPredict^2
  res <- res[testTimetoMCI$YearNLtoMCI<1.4]
  logitMAD <- append(logitMAD,mean(abs(res)))
  
  bgmd <- baggedModel(as.character(baggedformula2),trainTimetoMCI,type="LM")
  upre <- predict(bgmd$bagged.model,testTimetoMCI)
  plot(testTimetoMCI$YearNLtoMCI~upre)
  res <- testTimetoMCI$YearNLtoMCI^2-upre^2
  res <- res[testTimetoMCI$YearNLtoMCI<1.4]
  baggMAD <- append(baggMAD,mean(abs(res)))

  print(svmMAD)
  print(logitMAD)
  print(baggMAD)

  mp <- medianPredict(as.character(baggedformula2),CASESNLtoMCI,testWithNL,type="SVM")

#  mp$predictions[,-1] <- 2*exp(mp$predictions[,-1])
  mp$predictions[,-1] <- mp$predictions[,-1]^2
  cdft <- NULL
  x <- (1:60)/12
  tsamples <- length(baggedformula2)
  for (i in 1:nrow(mp$predictions))
  {
    nd <- mp$predictions[i,-1]
    if ((sna <- sum(is.na(nd))) > 0)
    {
      if (sna > tsamples/2)
      {
        nd <- numeric(tsamples) 
      }
      else
      {
        nd <- nd[!is.na(nd)];
      }
    }
    fn <- ecdf(as.numeric(nd))
    cdft <- rbind(cdft,fn(x))
  }
  rownames(cdft) <- rownames(mp$predictions)
  write.csv(cdft,file=paste(repp,"SVMTimetoMCITimeCDF.csv",sep="_"))
  write.csv(mp$predictions,file=paste(repp,"SVMTimetoMCITimePrediction.csv",sep="_"))
  
  mpl <- medianPredict(as.character(baggedformula2),CASESNLtoMCI,testWithNL,predictType ="linear",type="LM")
#  mpl$predictions[,-1] <- 2*exp(mpl$predictions[,-1])
  mpl$predictions[,-1] <- mpl$predictions[,-1]^2
  cdft <- NULL
  x <- (1:60)/12
  mpre <- mpl$predictions
  for (i in 1:nrow(mpl$predictions))
  {
    nd <- mpl$predictions[i,-1]
    if ((sna <- sum(is.na(nd))) > 0)
    {
      if (sna > tsamples/2)
      {
        nd <- numeric(tsamples) 
      }
      else
      {
        nd <- nd[!is.na(nd)];
      }
    }
    fn <- ecdf(as.numeric(nd))
    cdft <- rbind(cdft,fn(x))
  }
  rownames(cdft) <- rownames(mpl$predictions)
  write.csv(cdft,file=paste(repp,"LMTimetoMCITimeCDF.csv",sep="_"))
  write.csv(mpl$predictions,file=paste(repp,"LMTimetoMCITimePrediction.csv",sep="_"))
  allformulas <- append(allformulas,as.character(baggedformula2))
}

plot(alltestpredicts[,1]~alltestpredicts[,2],main="All Tests")
tsamples <- length(allformulas)

mpl <- medianPredict(allformulas,CASESNLtoMCI,testWithNL,predictType ="linear",type="LM")
#mpl$predictions[,-1] <- 2*exp(mpl$predictions[,-1])
mpl$predictions[,-1] <- mpl$predictions[,-1]^2
cdft <- NULL
x <- (1:60)/12
sd(mpl$predictions[30,-1])
nelem <- nrow(mpl$predictions[,-1])*ncol(mpl$predictions[,-1])

mpl$predictions[,-1] <-  mpl$predictions[,-1]+as.data.frame(matrix(rnorm(nelem,0,mean(logitMAD)),nrow=nrow(mpl$predictions)));
sd(mpl$predictions[30,-1])

for (i in 1:nrow(mpl$predictions))
{
  nd <- mpl$predictions[i,-1]
  if ((sna <- sum(is.na(nd))) > 0)
  {
    if (sna > tsamples/2)
    {
      nd <- numeric(tsamples) 
    }
    else
    {
      nd <- nd[!is.na(nd)];
    }
  }
  fn <- ecdf(as.numeric(nd))
  cdft <- rbind(cdft,fn(x))
}
rownames(cdft) <- rownames(mpl$predictions)
write.csv(cdft,file=paste(repp,"FinalMCITimeCDF.csv",sep="_"))
write.csv(mpl$predictions,file=paste(repp,"FINALTimetoMCITimePrediction.csv",sep="_"))
write.csv(allformulas,file=paste(repp,"AllFormulasFinalTimetoMCI.csv",sep="_"))

LastTime_NL <- testLastTimePointWithNL
LastTime_NL$YearNLtoMCI <- numeric(nrow(LastTime_NL))

mpl <- medianPredict(allformulas,CASESNLtoMCI,LastTime_NL,predictType ="linear",type="LM")
#mpl$predictions[,-1] <- 2*exp(mpl$predictions[,-1])
mpl$predictions[,-1] <- mpl$predictions[,-1]^2
cdft <- NULL
x <- (1:60)/12
sd(mpl$predictions[10,-1])
nelem <- nrow(mpl$predictions[,-1])*ncol(mpl$predictions[,-1])

mpl$predictions[,-1] <-  mpl$predictions[,-1]+as.data.frame(matrix(rnorm(nelem,0,mean(logitMAD)),nrow=nrow(mpl$predictions)));
sd(mpl$predictions[10,-1])
sum(is.na(mpl$predictions[,-1]))
i=nrow(mpl$predictions)
for (i in 1:nrow(mpl$predictions))
{
  nd <- mpl$predictions[i,-1]
  if ((sna <- sum(is.na(nd))) > 0)
  {
    if (sna > tsamples/2)
    {
      nd <- numeric(tsamples) 
    }
    else
    {
      nd <- nd[!is.na(nd)];
    }
  }
  fn <- ecdf(as.numeric(nd))
  cdft <- rbind(cdft,fn(x))
}
rownames(cdft) <- rownames(mpl$predictions)
write.csv(cdft,file=paste(repp,"FinalLastObservationMCITimeCDF.csv",sep="_"))
write.csv(mpl$predictions,file=paste(repp,"FINALLastObservationTimetoMCITimePrediction.csv",sep="_"))



mpl <- medianPredict(allformulas,CASESNLtoMCI,testWithNL,type="SVM")
#mpl$predictions[,-1] <- 2*exp(mpl$predictions[,-1])
mpl$predictions[,-1] <- mpl$predictions[,-1]^2
cdft <- NULL
x <- (1:60)/12
nasp <- mpl$predictions[is.na(mpl$predictions[,2]),]

i=nrow(mpl$predictions)
for (i in 1:nrow(mpl$predictions))
{
  nd <- mpl$predictions[i,-1]
  if ((sna <- sum(is.na(nd))) >0)
  {
    if (sna > tsamples/2)
    {
      nd <- numeric(tsamples) 
    }
    else
    {
      nd <- nd[!is.na(nd)];
    }
  }
  fn <- ecdf(as.numeric(nd))
  cdft <- rbind(cdft,fn(x))
}
rownames(cdft) <- rownames(mpl$predictions)
write.csv(cdft,file=paste(repp,"FinalMCITimeCDF_SVM.csv",sep="_"))
write.csv(mpl$predictions,file=paste(repp,"FINALTimetoMCITimePrediction_SVM.csv",sep="_"))


barplot(cbind(svmcor,logitcor),beside=TRUE)
barplot(cbind(svmMAD,logitMAD),beside=TRUE)


```
